PLANE_SIZE = 1000          
MIN_NODES = 20
MAX_NODES = 30
MIN_CLUSTERS = 4
MAX_CLUSTERS = 6
CLUSTER_STD = 55            
CLUSTERED_NODE_RATIO = 0.8  
MIN_DEGREE = 2
MAX_DEGREE = 4
HARD_DEGREE_CEILING = 6

MIN_INDEPENDENT_CLUSTER_LINKS = 2

DELAY_MS_PER_UNIT_DISTANCE = 1.0   
JITTER_RATIO = 0.2                 

HOST = "127.0.0.1"
NODE_BASE_PORT = 15000       
SIMULATOR_CONTROL_PORT = 14999  

DEFAULT_STEM_PROBABILITY = 0.5   
DANDELION_EMBARGO_SECONDS = 3.0

DEFAULT_NUM_PACKETS = 200
DEFAULT_PROPAGATION_GRACE_SECONDS = 5.0  
OUTPUT_DIR = "output"
SIMULATION_LOG_FILENAME = "simulation.log"     
GROUND_TRUTH_LOG_FILENAME = "ground_truth.log"  
REFERENCE_TRUTH_FILENAME = "reference_truth.jsonl"
SPY_OBSERVATIONS_FILENAME = "spy_observations.jsonl"
MANIFEST_FILENAME = "manifest.json"
NODE_IDS_FILENAME = "node_ids.json"
TOPOLOGY_FILENAME = "topology.json"
TOPOLOGY_PNG_FILENAME = "topology.png"

LOG_FIELD_SEPARATOR = " | "
